### ISSUE TITLE
viewport=full does not resize to correct width

### ISSUE THREAD

**Issue by bettertest-org** [scrapinghub/splash#145]
Png is too narrow when setting viewport to full.

Example pages to grab:
http://allegro.pl/ShowItem2.php?item=4892071886
http://allegro.pl/ShowItem2.php?item=4879256257 

viewport cannot be set to fixed parameters because height is different

**Comment by kmike** [comment]
Hi,

This PR can be related: https://github.com/scrapinghub/splash/pull/131

**Comment by kmike** [comment]
The described issue is fixed in master.

By default, page loading still fails though, because some requests to ftp resources take too long to finish. After filtering out those requests page renders fine. So I'm closing this issue.

There is a ticket for allowing to stop rendering without waiting for the full page load: https://github.com/scrapinghub/splash/issues/127
