### ISSUE TITLE
Use of proxies

### ISSUE THREAD

**Issue by cp2587** [scrapinghub/splash#206]
Hi,
We are using a rotating pool of proxies to change our ip periodically while doing scraping and we would like to tell splash which one to use on a request basis. I know we can use the "proxy profile" setting but it seems cumbersome to have to change the .ini file each time one of the proxy is changed. Is there a way to pass the proxy settings along with the request to splash ? If not, is this for security reasons (since splash has no user management) ?

Great work nonetheless !

**Comment by kmike** [comment]
Hi @cp2587,

It is not possible, but I'm working on it right now. See https://github.com/scrapinghub/splash/issues/204, https://github.com/scrapinghub/splash/issues/160 and https://github.com/scrapinghub/splash/pull/179.

**Comment by kmike** [comment]
Fixed by https://github.com/scrapinghub/splash/pull/207.

You can give [splash:on_request()](http://splash.readthedocs.org/en/latest/scripting-ref.html#splash-on-request) a try. Currently Splash master branch is needed to use this feature (see http://splash.readthedocs.org/en/latest/install.html#splash-versions).
