### ISSUE TITLE
Deprecate and remove Splash-as-a-proxy feature

### ISSUE THREAD

**Issue by kmike** [scrapinghub/splash#236]
What about deprecating and removing [Splash-as-a-proxy](http://splash.readthedocs.org/en/latest/api.html#splash-as-a-proxy) feature? 

It doesn't work with https (see https://github.com/scrapinghub/splash/issues/199), and likely never will. By removing this feature we can save user time: they won't invest in integration with proxy mode only to discover it doesn't work for them. It will also reduce and simplify the codebase and reduce the dependency on advanced Twisted features.

**Comment by kmike** [comment]
Another issue: https://github.com/scrapinghub/splash/issues/241.

**Comment by pawelmhm** [comment]
can we do it and deprecate it? it's a real pain to maintain all splash-as-proxy features, it slows down development because you have to adapt to edge cases of splash as proxy, also many things are not even tested with splash-as-proxy so we dont even know if they work ok. 

do we know about any users who use it? is there some way to notify them about deprecation?

**Comment by kmike** [comment]
I don't know how to deprecate such features. Probably the best way forward is to just remve it for Splash 2.0.
