### ISSUE TITLE
User agent not set correctly when specifying a base url

### ISSUE THREAD

**Issue by Youwotma** [scrapinghub/splash#290]
Test script:
```
function main(splash)
  local url = 'http://httpbin.org/headers?nocache=' .. math.random()
  splash:set_user_agent('FooBar/1.0')
  assert(splash:go(url, 'http://httpbin.org'))
  assert(splash:wait(0.5))
  return {
    html = splash:html(),
    png = splash:png(),
    har = splash:har(),
  }
end
```
Uses `Mozilla/5.0` instead of `FooBar/1.0`.

Specifying the user agent as a header works.

**Comment by pawelmhm** [comment]
you're right, and it also seems like "accept" header is missing too, looks like no headers are set on request, simple test reproducing this:

https://github.com/pawelmhm/splash/commit/a84c3d7ffbb901f8cb7c3b7d74670c6f36e3a137

**Comment by pawelmhm** [comment]
Aha! This is because user_agent is set on [web_page object](https://github.com/scrapinghub/splash/blob/master/splash/browser_tab.py#L832) and when we pass "base_url" we never load url into webpage but we [bypass webpage completely](https://github.com/scrapinghub/splash/blob/master/splash/browser_tab.py#L302)

**Comment by pawelmhm** [comment]
hey @kmike @Youwotma seems like we dont set UA at all for all manual forms of requests, e.g. if you do splash:http_get() or splash:http_post() request from Splash will not have UA. If you do go() request will have default Splash UA. Should we consider this a bug? By default if you use HTTP API or go() without base url you get UA: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) splash Safari/538.1" so not having UA in http_get() or http_post() is inconsistency.

**Comment by kmike** [comment]
I think it makes sense to use default headers in http_get and http_post.

**Comment by pawelmhm** [comment]
and same for go with base url right? so we should have default UA for all those requests. I'm not sure how websites would handle reqeusts without any UA, perhaps no big deal but could be trouble in some cases?

**Comment by kmike** [comment]
yeah, right

**Comment by pawelmhm** [comment]
and did you mean UA or all headers? Because QWebPage also adds "Accept: text/html" header, which is also missing

**Comment by kmike** [comment]
I think `Accept: text/html` is not a good default for http_get/http_post. E.g. requests library [uses](https://github.com/kennethreitz/requests/blob/00fa5f171c9366c9b61d633aa1218b5bcb866f99/requests/utils.py#L585) `Accept: */*` which makes more sense.

Re other header: I think it is fine to use headers set by splash:set_custom_headers in http_get/http_post, but there should be a way to override it just for a single request. Currently we only adding or replacing headers using `headers` argument; it works because default set of headers is empty.

**Comment by pawelmhm** [comment]
>  there should be a way to override it just for a single reques

I see in docs that there is request:set_header(name, value) so that would probably be the way to do it?

**Comment by pawelmhm** [comment]
would be nice to have some settings where users could set default headers, but I see that https://github.com/scrapinghub/splash/pull/279/files is stalled now, perhaps worth prioritizing it sounds like a really useful PR and lots of work already done
