### ISSUE TITLE
Is --maxrss and --memory causing docker daemon to stuck?

### ISSUE THREAD

**Issue by ohade** [scrapinghub/splash#304]
could running multiple instance of splash like this:
docker run -d -p 8050:8050 --memory=2G scrapinghub/splash:latest --maxrss 2000
be a reason for docker to freeze?
I saw in the example to how to run the splash that the --memory flag was set to 4.5G and the maxrss was set to only 4000, why so?

I am trying to find out why the docker seems to freeze after a while and i cannot communicate with it.
I eliminated a bunch of stuff and i came to this option.

I am now running the splash containers with maxrss 1500:
docker run -d -p 8050:8050 --memory=2G scrapinghub/splash:latest --maxrss 1500

and for now it look ok, so what can the reason be?
Thanks

**Comment by kmike** [comment]
> I saw in the example to how to run the splash that the --memory flag was set to 4.5G and the maxrss was set to only 4000, why so?

Docker checks memory usage of a process often and kills the container if memory usage is exceeded. 
--maxrss monitor checks peak memory usage every minute (i.e. much less frequently) and shuts down Splash if peak memory usage was larger than a specific value. 

--maxrss is intended to be a standard way to keep memory usage in control: Splash has enough memory, memory usage grows slowly because of webkit memory leaks, and Splash is restarted from time to time automatically to keep it in control. Docker memory limits are intended to be an extra protection measure: memory usage may grow too fast for --maxrss, or memory usage may grow without returning control to the event loop.

> docker run -d -p 8050:8050 --memory=2G scrapinghub/splash:latest --maxrss 1500

Do you use docker --restart option or some other way to monitor containers? Without --restart memory limits will just kill containers.

1.5G should be enough if you render HTML or small screenshots; large screenshots (e.g. `render_all=1`) can cause problems (Splash may be restarting often).

I've seen issues with --maxrss (it didn't work), but I can only reproduce them with qt5. See https://github.com/scrapinghub/splash/commit/3a277e0b9d3adbc6289fc4b6ee332348c9a7631f. 

See also: https://github.com/TeamHG-Memex/aquarium - it has some example configs which may be useful for you.

Sorry, I don't have a direct answer for your questions, but hope this information helps.

**Comment by ohade** [comment]
Thanks for the response, 
At first i used the --restart flag, later i decided that i want to know and control when the container restarts again and so i removed the flag and monitor it myself.

**Comment by kmike** [comment]
To clarify: when you're talking about freezing, does it mean container is displayed in `docker ps`, but you can't access it using docker commands (`docker exec`, `docker logs`)?

**Comment by ohade** [comment]
No, the i mean that docker ps/info/image/... is unresponsive

**Comment by kmike** [comment]
Hm, I'd say this suggests some problems with docker daemon, not with software in a docker container.

**Comment by ohade** [comment]
I know, but I thought that maybe splash caused some unique circumstances
that could have triggered this.

**Comment by kmike** [comment]
@ohade thanks for letting us know about problems you have; this information is valuable, and it may help someone in future. But I'm not sure we can do anything in Splash, so I'm closing this ticket.

**Comment by kmike** [comment]
@ohade an update: I've been bitten by docker daemon freezes as well. After checking syslog I think in my case the most likely reason is https://github.com/docker/docker/issues/5618. 

Maybe it is the same issue (check syslog to be sure). It may looked related to `--maxrss` because when max rss limit hits container is restarted, at restart it dumps logs to disk(?), this causes high IO and triggers Linux kernel bug.

**Comment by shangliuyan** [comment]
@ohade I meet same problem, when splash memory reach the --maxrss limit.And when the docker restart,it print this:
`unregister_netdevice: waiting for lo to become free. `
so,base @kmike answer, i change --maxrss  from 2048m to 800m.it work ok,and never have problem.
just as kmike said, maybe huge request cause the linux kernel bug or docker bug, if we use it carefuly it will be ok

**Comment by DimaMir999** [comment]
It would be good to add information from this discussion to official documentation because I faced with the same problem and spend a lot of time before finding this. I mean not only info about flag --maxrss but also the explanation about reason and some heuristic formula to calculate a good value for --maxrss.

**Comment by andrewtheis** [comment]
I'm running into this issue, but the memory usage doesn't even come close to the limit I have set. Splash just seems to be locking up.

**Comment by callumCarsnip** [comment]
@andrewtheis I was seeing the same problem and eventually lowered the --maxrss down to 400 with a memory limit at 560. I presume the reason why splash would lock up before reaching the memory limit is due to not having that amount of resources available, and therefore would just crash before resetting.
