### ISSUE TITLE
Drop Python 2 support?

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#381]
Tests pass fine in Python 3, Python 2 build is marked as can fail which means developers may not pay sufficient attention to it.

Can we officially drop Python 2 support now? Is there something blocking us from dropping Python 2 support? 

If we do drop Python 2 we could also start cleaning up codebase and removing all hacks that were added to support 2, it would probably improve code quality and reduce complexity.

**Comment by kmike** [comment]
Python 2 tests are skipped because 75% of times they hang on Travis for unknown reason. When executed locally, they pass for me. Documented Splash interface is HTTP API, but I wonder if there are users who use Splash directly (Portia?). There are also users who install Splash without Docker, they may want to use Python 2. 

-0 from me to drop Python 2 support (or -1 if it breaks Portia). IMHO it is not a big deal to drop Python 2 support, but it also doesn't provide much benefits on itself. A compelling reason to drop Python 2 support could be e.g. a move from twisted to https://github.com/harvimt/quamash and asyncio, given that it fixes some problems with qt5-reactor.

//cc @Youwotma

**Comment by Youwotma** [comment]
At the moment Portia uses py2 splash, but I think Scrapy was our latest py3 blocker so it looks like we could migrate Portia to py3 soon

**Comment by genius001** [comment]
IMHO, keep the current version of py2/py3. doesn't provide much benefits on itself.
And create a newly py3 version.

It would probably improve code quality and reduce complexity and workload, and keep users who use Portia.

**Comment by kmike** [comment]
Python 2 support will be dropped in Splash 3.0; it is already dropped in Splash master.
