### ISSUE TITLE
splash:wait_for_resume() should return 400 Bad Request if `splash` argument is missing in JavaScript code

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/splash#388]
splash:wait_for_resume takes javascript source as argument, js must be function with signature

```javascript
function main (splash) {}
```

when there is no main we return 400 bad request, but when there is no splash argument we dont. But seems like JS wont be successful without splash. Javascript function will simply time out.

I think we should return 400 if there is no splash argument so that user gets immediate feedback about what he is doing wrong just like we do in case of missing main.

**Comment by kmike** [comment]
@pawelmhm in JavaScript you can access function arguments without defining them, e.g.

```js
var x = function(){return arguments[0]}
x('splash')  // <- this returns 'splash'
```

so not defining `splash` argument is not an error.

Also, it looks quite hard to detect this specific error case because JS introspection is close to non-existing (you have to parse function source as text yourselves). 

Because of these two reasons -0 to fix that.
