### ISSUE TITLE
How to send unquot url?

### ISSUE THREAD

**Issue by jackmasa** [scrapinghub/splash#403]
Expect:
`http://www.baidu.com/?wd=<h1>xsser`

Fact:
`http://www.baidu.com/?wd=%3ch1%3exsser`

**Comment by pawelmhm** [comment]
if you're sending request to Splash with GET request url argument must be urlencoded so that special characters in target url dont interfere with Splash querystring, e.g. you want to render http://httpbin.org/get?foo=bar if you dont quote url foo=bar will be processed by Splash and not by target website. If for some reason you dont want to quote url just use POST endpoint and post your url as json. This is described in documentation: http://splash.readthedocs.org/en/stable/api.html
