### ISSUE TITLE
iframe cant download

### ISSUE THREAD

**Issue by wusy1209** [scrapinghub/splash#413]
why the url of iframe is download,but the iframe content is not in the father page?

**Comment by Youwotma** [comment]
Hi @wusy1209,

in the HTML output of the page you only get the rendered content of the original page, the page in the iframe is in a different page, so it's not included.

To get it, you can use the `render.json` endpoint and the `iframes=1` parameter ([docs](https://splash.readthedocs.org/en/stable/api.html#render-json))

David

**Comment by wusy1209** [comment]
@Youwotma  Thanks!

when i use `render.json`,then i can get the page of the iframes,but how can i put proxy and cookies ,headers for each request?

Wu

**Comment by Youwotma** [comment]
@wusy1209 If you want to get the frame's content from lua, you can use `splash:evaljs("frames[0].document.documentElement.outerHTML")` (sustitute 0 for the frame number, between 0 and frames.length)

**Comment by wusy1209** [comment]
@Youwotma thanks very much
it is a good solution for iframes page. now, in my spider, many sites has  iframes, so i must write different lua script to solve that.
do you think can `splash  execute` get iframe with it's page directly in the future ?

**Comment by Youwotma** [comment]
If you mean returning the iframe's html inside the `splash:html()` result (for example, by embedding it in the iframe's srcdoc attribute), I don't think it's a good idea because it's not the actual content of the DOM (and you are overwriting the original srcdoc, which may is different to the rendered iframe HTML). If you are thinking about adding a new `splash:frames_html()` function, it might be a good idea if a lot of people need it, but it can be implemented by the script with the available functions, so maybe it's a better idea to provide it as a external library (we are thinking about making a library of utility functions for splash scripts).

**Comment by genius001** [comment]
I'm agree with @Youwotma 
It can be implemented by the script with the available functions.
Splash scrpt can do almost things use the available functions.

**Comment by wusy1209** [comment]
That is nice, Thanks @Youwotma ,@genius001

**Comment by 0xIslamTaha** [comment]
@dvdbng Is there anyupdates about `splash:frames_html()`?

**Comment by cbreland** [comment]
@dvdbng, `splash:frames_html()` would make things so much easier when you need to pass cookies and render frames. Also, I have noticed that sometimes a frame does not get rendered when using a `splash:evaljs("frames[0].document.documentElement.outerHTML")`  expression.
