### ISSUE TITLE
Ability to pass URL with parameters?

### ISSUE THREAD

**Issue by krsyoung** [scrapinghub/splash#435]
I'm making use of the [render.html](http://splash.readthedocs.org/en/stable/api.html#render-html) API call but have hit a snag in trying to pass along parameters.  The URL I need to render looks like:

    http://somesite.com?id=1234&secret=1234

Inevitably the site comes back from Splash indicating that I haven't provided credentials (id and secret). I'm guessing that Splash is interpreting (ignoring) the parameters and that they aren't being sent as a part of the `?url=` value.  My full call looks like:

    http://mysplash:8050/render.html?timeout=10&url=http://somesite.com?id=1234&secret=1234

Any chance somebody has a nice workaround on how I can either URI encode the `url=` parameter?

**Comment by kmike** [comment]
Hey @krsyoung,

GET parameter values must be URL encoded, it is not enough to concatenate strings; this issue is not specific to Splash. In Python there is https://docs.python.org/2/library/urllib.html#urllib.urlencode function, or you can use requests library which can also encode parameters for you. In JavaScript [encodeURIComponent](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) should be called on all parameter names and values.

Alternative way is to use `application/json` POST requests - you can put all parameters in a JSON-encoded POST body. With `requests` library this is super-easy:

```py
import requests
resp = requests.post(SPLASH_URL + "/render.html", json={
    'url': 'http://somesite.com?id=1234&secret=1234',
    'timeout': 10,
})
html = resp.text 
```

**Comment by krsyoung** [comment]
Slam dunk, will go with the JSON POST approach, thanks @kmike :+1:
