### ISSUE TITLE
When I send request with lua script, I got 400 error

### ISSUE THREAD

**Issue by gamelife1314** [scrapinghub/splash#477]
`# coding:utf-8
import requests

request = requests.post('http://127.0.0.1:8050/execute', data={
    'har':1,
    'html':1,
    'http_method':'GET',
    'images':1,
    'lua_source':'''
    function main(splash)
        local url = splash.args.url
        assert(splash:go(url))
        assert(splash:wait(0.5))
        return {
            html = splash:html(),
            png = splash:png(),
            har = splash:har(),
        }
    end
    ''',
    'png':1,
    'render_all':False,
    'resource_timeout':0,
    'save_args':[],
    'timeout':60,
    'url':'http://mp.weixin.qq.com/s?timestamp=1467478406&src=3&ver=1&signature=Dws5bhm8YiaBsgaEHre7Cdg5sidfbbEnSdUaDkS1rq-4o3KbUiQt5yLxxU48*Aw2KzU2h8eTz-HK7m4*vlCAlhb*S3C3JNGh71Asu8Suvurmo5a*6JIDlu7JKBFfG88XD7ovwQNCyqQ0NNyRcdieOCmnLcsPxVOgfTMIM-5ITXw=',
    'viewport':'1024x768',
    'wait':0.5
}, headers={'Content-Type':"application/json"})

print request.status_code
print request.text`

error msg:

400
{"description": "Incorrect HTTP API arguments", "type": "BadOption", "info": {"description": "Can't decode JSON", "message": "Expecting value: line 1 column 1 (char 0)", "type": "invalid_json"}, "error": 400}

**Comment by lopuhin** [comment]
@gamelife1314 Splash API expects JSON-encoded body if you are making a post request (http://splash.readthedocs.io/en/stable/api.html#splash-http-api), but if ``data`` argument to ``requests.posts`` is a dict, it encodes them as form-encoded data.
So instead of ``requsts.post(url, data={..}, headers={'Content-Type':"application/json"})`` you can use ``requsts.post(url, json={..})`` (http://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests)

**Comment by gamelife1314** [comment]
@lopuhin thank you
