### ISSUE TITLE
Core Dumped with bad encoded statusText

### ISSUE THREAD

**Issue by gabrii** [scrapinghub/splash#521]
![report](https://cloud.githubusercontent.com/assets/3278243/19921622/00055bb4-a0df-11e6-911b-7fc63e26dafa.png)

```
2016-10-31 19:27:48.122537 [-] "127.0.0.1" - - [31/Oct/2016:18:27:47 +0000] "POST /render.json HTTP/1.1" 200 22263 "-" "python-requests/2.11.1"
Traceback (most recent call last):
  File "splash/network_manager.py", line 334, in _on_reply_headers
    har.store_reply_headers_received(self._get_request_id(request), reply)
  File "splash/har_builder.py", line 165, in store_reply_headers_received
    entry["response"].update(reply2har(reply))
  File "splash/har/qt.py", line 125, in reply2har
    res["statusText"] = bytes(status_text).decode('latin1')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 18-19: ordinal not in range(128)
Aborted (core dumped)
```

The `repr()` of `status_text` before the error is `u'Przekierowanie sta\xc5\x82e'`

Reproducible, but I can't disclose the URL publicly. If someone whats it I can send it through email.

**Comment by nyov** [comment]
This is somewhat a server-side issue. According to [RFCs](https://tools.ietf.org/html/rfc7230), HTTP Headers should/must be US-ASCII/latin-1 encoded. What this server sends as status header is bad / should be ignored.

    Historically, HTTP has allowed field content with text in the
    ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
    through use of [RFC2047] encoding.  In practice, most HTTP header
    field values use only a subset of the US-ASCII charset [USASCII].
    Newly defined header fields SHOULD limit their field values to
    US-ASCII octets.  A recipient SHOULD treat other octets in field
    content (obs-text) as opaque data.

Also see https://tools.ietf.org/html/rfc7230#section-3.2.6

HOWEVER, [Section 3.1.2](https://tools.ietf.org/html/rfc7230#section-3.1.2) for the Status header specifically, states that:

    The reason-phrase element exists for the sole purpose of providing a
    textual description associated with the numeric status code, mostly
    out of deference to earlier Internet application protocols that were
    more frequently used with interactive text clients.  A client SHOULD
    ignore the reason-phrase content.

So this _could_ be considered a bug in scrapy/splash, which should **ignore**/cut off the reason text instead of trying to handle it.

**Comment by kmike** [comment]
Fixed by https://github.com/scrapinghub/splash/pull/528.
