### ISSUE TITLE
"CRITICAL:Could not find any packages to operate on"

### ISSUE THREAD

**Issue by gabrii** [scrapinghub/splash#524]
I've not been able to reproduce this. But the whole splash hanged, without any other error, and hanging the requests in progress forever. It launched a GUI dialog which I dismissed by accident...

I'm gonna start logging everything with verbosity=5 and report back.

This bugs me a lot, because with the segmentation faults or core dumps I can just detect it and relaunch. I might have to create a script which detects this logging message and restarts splash.

**Comment by gabrii** [comment]
Here you go! ![screenshot_2016-11-09_09-38-34](https://cloud.githubusercontent.com/assets/3278243/20131896/9a7321a0-a660-11e6-8f69-a8d376d2b94a.png)

And after clicking close, the message "CRITICAL:Could not find any packages to operate on" appears, meanwhile splash is hanged.

**Comment by kmike** [comment]
That's strange; error message doesn't make sense to me. I guess I don't see these kinds of issues because Splash is usually executed headlessly in Docker, and even if Splash hangs I can't see the window. So it is really helpful you're running it without Docker. 

We also don't check Splash in Python 2.x often; Docker image uses Python 3.4. Maybe it is time to even drop Python 2 support - we're running tests on Python 2, but they are allowed to fail because they hang sometimes, and there is no much incentive to investigate this. Portia uses Splash in Python 2.x though, so it should be coordinated with them (but there is some work on Python 3 porting, https://github.com/scrapinghub/portia/issues/624).

Do you have [splash.plugins_enabled](http://splash.readthedocs.io/en/stable/scripting-ref.html#splash-plugins-enabled) set to true?

**Comment by gabrii** [comment]
I'll try the 3.4 version if it's more supported. All our stack is in 2.7, but being a rest service I don't expect any problems with that. On production it will run headless anyway, so I won't see the dialog,.. Hoping it doesn't hang anyway!

Given that the docs say splash.plugins_enabled is False by default, and I haven't modified it, I would say it's set to False.

**Comment by gabrii** [comment]
Switched to py3. Now I've intercepted the message a little bit earlier, it doesn't show much more information, but maybe it helps. 
![screenshot_2016-11-11_17-00-03](https://cloud.githubusercontent.com/assets/3278243/20221144/7f4d243a-a830-11e6-9a85-4a0fab76f275.png)

I'm still getting Segmentation Faults  quite frequently (every 3000 requests to /render.json more or less), see #444 .

**Comment by gabrii** [comment]
I found what's causing the dialog:
`/usr/bin/python3 /usr/bin/gstreamer-codec-install gstreamer|1.0|python|text/html decoder|decoder-text/html`

I've uninstalled it, it was in the package `sesssioninstaller` , and I think it's not installed in ubuntu server. I'll update if it stops the problem.

**Comment by kmike** [comment]
@gabrii thanks for the investigation! Do you know if it affects official docker image?

**Comment by gabrii** [comment]
I don't know if it affects the docker image, but I wouldn't expect it to have this package. 

It didn't hang once after removing the package, I'm considering this closed (as running Splash in a desktop environment it's not the typical use case, and fixing it is as simple as removing this non-vital package).
