### ISSUE TITLE
Possible to update webkit version?

### ISSUE THREAD

**Issue by ben-xo** [scrapinghub/splash#541]
Hello,

Trying to figure out how to render some parts of pages which show fine in Safari but don't yet in Splash. Think it's that webkit is so far out of date.

What's the approach needed to move to a more modern webkit? I can't find any open tickets about it.

**Comment by kmike** [comment]
Hey @ben-xo,

I think there are two approches:

1. Add QtWebEngine (i.e. Chromium) support - there is an open ticket for that https://github.com/scrapinghub/splash/issues/349;
2. Switch from qt's built-in QtWebKit to this fork: https://github.com/annulen/webkit

This is a big issue; maybe we need to do both. (1) has an advantage of being supported by Qt folks and easy availability, but it is impossible to support all Splash features using QtWebEngine, so it should be an addition, not a replacement. 

(2) also looks promising; the code is not even alpha, but maintainers are doing great job - it is a huge amount of work to modernize WebKit version and integrate it with Qt. There is a third-party Debian package for it - https://gitlab.com/paretje/qtwebkit.

I want to take a look at it before the next release, but there is no a timeframe. 

If you want get the ball rolling the easiest way it to try making Splash work with QtWebKit fork instead of built-in QtWebKit - just install it, make sure this is what is used by PyQT, then try running Splash, and let us know how it goes.

**Comment by ben-xo** [comment]
Thanks for pointing me in the right direction @kmike. The third-party debian package looks promising, but my Debian-foo isn't; quite strong enough to know if I need to do more than follow the "build from source" instructions to emit a .deb, then update the Docker container to install that instead of qt55webkit - or if there are any further hoops I'd need to jump through. (For example, updating dependencies or forcing them to be ignored).

I've asked a similar question here: https://gitlab.com/paretje/qtwebkit/issues/1 . 

In my particular case, the thing which I'm trying to get working is CSS Flexbox support. 

The irony is that this is all in an attempt to work around a Safari same-origin bug (where you can't ask Safari to render a PNG of a canvas of an SVG of some HTML that you generated yourself, to create a downloadable graphic; even though this works just fine in Chrome and Firefox).

**Comment by kmike** [comment]
WebKit version is updated in Splash master.
