### ISSUE TITLE
init.d Script

### ISSUE THREAD

**Issue by michaelgohl** [scrapinghub/splash#552]
Hey Guys,

currently I start splash with the following command /usr/bin/nohup python3 -m splash.server -v0 &

Is there a way to start splash with an init.d script? 

Best Regards
Micha

**Comment by kmike** [comment]
There must be a way; the way to go is to consult with init.d documentation :) You need to figure out how to run a non-daemon script in background (maybe nohup or a similar utility could help). Adding a watchdog is a good idea because Splash process could exit. There are other options like supervisord, upstart or systemd. Example upstart script is available here: https://github.com/scrapinghub/splash/blob/master/debian/upstart. If you have Docker installed you can also use daemonize Splash using Docker, as described in http://splash.readthedocs.io/en/stable/faq.html#hard-way.

I'm not sure maintaining init.d script in the Splash repo is a good idea, so I'm closing this ticket. For development daemonizing is not needed, and for production using load-balanced instances with a proxy and request queue in front of Splash (as described in docs) is a better idea; single-process Splash without a request queue in front of it could cause issues in practice ( http://splash.readthedocs.io/en/stable/faq.html#splash-instance-is-overloaded). See also: https://github.com/TeamHG-Memex/aquarium.
