### ISSUE TITLE
Current version of Docker working for proxies? 

### ISSUE THREAD

**Issue by wflanagan** [scrapinghub/splash#559]
I'm not sure if I'm doing something wrong.. but I cannot get splash to work through either Crawlera Proxies, or TrustedProxies (our current proxy provider), both commercial providers (yes, I'm aware that Crawlera is YOUR proxy service). 

Splash is rejecting the request, saying an authentication error.  I have literally spent all day working on this.. and have triple verified that the authentication parameters are correct. These are used in production, running thousands upon thousands of requests per day. 

I have tried using the .ini method of initialization of proxies, as well as passing the URL. I am using the render.xxx method. All destinations tested, without proxies, pass through Splash without problems.  

I'm using an off the shelf Docker image... using docker compose.  I have a Gist that has my config in it (neutralized for username password and IP addresses). 

Again, I have confirmed that the username/password are correct. 

I'd love to use this, but without proxies, it's a no go.  Help? 

https://gist.github.com/wflanagan/2141dd9605948a435c81881694c4de7b

P.s. I can't seem to add a "question" label. I would if I could.

**Comment by kmike** [comment]
Sorry, I'm not sure how to reproduce it with Crawlera, and I don't have a TrustedProxies account. The following works for me:

```py
splash_url = 'http://<MY_SPLASH_SERVER>:8050/render.html'
resp = requests.post(splash_url, json={
    'url': 'http://httpbin.org/ip', 
    'proxy': 'http://<CRAWLERA_API_KEY>:@proxy.crawlera.com:8010'}
)
print(resp.text)  # the IP is changed when proxy is enabled
```

**Comment by wflanagan** [comment]
Hi,

This is using the render.html endpoint? I was talking about this all in the
context of the render.html. endpoint.

I will try to figure out scripting today.

**Comment by kmike** [comment]
Hey @wflanagan,

Yes, I used render.html and passed `'http://<CRAWLERA_API_KEY>:@proxy.crawlera.com:8010'` in the 'proxy' argument. I used a JSON POST request for render.html endpoint: body is a json-encoded `{'url': '...', 'proxy': '...'}` dict, and Content-Type header is set to `application/json`. 

The script I've pasted does that; it is not a Splash script, but a Python script which uses [requests](http://docs.python-requests.org/en/master/) library to send an HTTP request. If you're using Ruby there must be a way to do the same. 

JSON POST is an alternative way to send requests to Splash; it is preferrable because sometimes you need to pass a large argument, and URL length limits can be not enough; also, unlike GET parameters JSON has support for arrays and nested objects. That said, GET arguments should still be fine for your example.

I also noticed that in your example (`HTTP.get("http://splash:8050/render.html?proxy=http://username:password@123.234.345.456&url=https://audienti.com/")`) HTTP GET arguments are not url-escaped; I have zero experience with Ruby, but it seems something like https://ruby-doc.org/stdlib-2.4.0/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-GET+with+Dynamic+Parameters should be more robust.

I'm not saying you're using Splash incorrectly though, it could be a Splash bug, but to debug it it'd be great to have it working on a common simple example first!

**Comment by wflanagan** [comment]
To cover your statements/questions: 

1) URL escaping. I've done it both ways trying to troubleshoot. The default behavior would be to escape the URL. I jumped through some hoops to unescape it to see if that was the problem.  Going forward it will be escaped. 

2) I have tried both post and get requests, and both exhibit the same problem.  

3) Yes, Crawlera works now. 

The URL I'm using is available with basic auth, so I am happy to give you the real URL through a back channel, if you want to see or play with it.  

What should I show you to give you some data?

**Comment by kmike** [comment]
> The URL I'm using is available with basic auth, so I am happy to give you the real URL through a back channel, if you want to see or play with it.

To clarify, is it what the request chain looks like: `Client -> (splash auth?) -> Splash -> (crawlera auth) -> Crawlera -> (website auth) -> website`? 

It seems auth error could happen if you send HTTP Basic auth headers to Splash, while they're intended for a remote website. To send the header to a remote website use [headers](http://splash.readthedocs.io/en/stable/api.html#arg-headers) argument; you'll likely have to build Basic-Auth header manually (sorry, a Python example again, but it should be something similar in Ruby):

```py
import requests
from base64 import urlsafe_b64encode

proxy_url = 'http://<CRAWLERA-API-KEY>:@proxy.crawlera.com:8010'
splash_url = 'http://<SPLASH-ADDRESS>:8050/render.html'

def basic_auth_header(username, password):
    auth = ("%s:%s" % (username, password))
    return 'Basic ' + urlsafe_b64encode(auth.encode('latin1')).decode('ascii')

# headers to send to the remote website
remote_headers = {
    'Authorization': basic_auth_header('user', 'passwd')
    # 'Authorization': 'Basic dXNlcjpwYXNzd2Q='
}

# body of the request to Splash
json_body = {
    'url': 'http://httpbin.org/basic-auth/user/passwd',
    'proxy': proxy_url,
    'headers': remote_headers,
}

resp = requests.post(splash_url, json=json_body, 
    # if Splash itself is protected by HTTP Basic Auth:
    # auth=('SPLASH-USER', 'SPLASH-PASSWORD'),
)

print(resp.text)
```

The script above works for me. BUT it doesn't work if `'http://httpbin.org/basic-auth/user/passwd'` URL is changed to `'https://httpbin.org/basic-auth/user/passwd'` - Crawlera returns 'bad_auth' response, asking for Proxy-Authorization header.

There is a workaround though: proxy credentials set in a Lua script work both for HTTP and HTTPS website. It looks a lot like https://github.com/scrapinghub/splash/issues/344; it seems https://github.com/scrapinghub/splash/pull/348 fixed it for Lua scripts, but not for 'proxy' argument of render.xxx endpoints.

Using Lua script is better anyways if you're working with Crawlera because this allows to enable [Crawlera sessions](https://doc.scrapinghub.com/crawlera.html#sessions). It allows a more browser-like behavior where all requests (to the main page, to relative resources) are from the same IP address. Crawlera docs provide an [example](https://doc.scrapinghub.com/crawlera.html#using-crawlera-with-splash) or Crawlera+Splash integration using a Lua script; one can change it to enable HTTP Basic auth for remote websites:

```lua
-- myscript.lua
function main(splash)
    local host = "proxy.crawlera.com"
    local port = 8010
    local user = splash.args.crawlera_apikey
    local password = ""
    local session_header = "X-Crawlera-Session"
    local session_id = "create"

    splash:on_request(function (request)
        request:set_header("X-Crawlera-UA", "desktop")
        request:set_header(session_header, session_id)
        request:set_proxy{host, port, username=user, password=password}

        -- set up HTTP Basic Auth access to remote website
        request:set_header("Authorization", splash.args.remote_auth)
    end)

    splash:on_response_headers(function (response)
        if response.headers[session_header] ~= nil then
            session_id = response.headers[session_header]
        end
    end)

    splash:go(splash.args.url)
    return splash:html()
end
```

Then send this script to /execute endpoing:

```py
import requests
from base64 import urlsafe_b64encode


proxy_url = 'http://<CRAWLERA-API-KEY>:@proxy.crawlera.com:8010'
splash_url = 'http://<SPLASH-ADDRESS>:8050/execute'

def basic_auth_header(username, password):
    auth = ("%s:%s" % (username, password))
    return 'Basic ' + urlsafe_b64encode(auth.encode('latin1')).decode('ascii')

with open('myscript.lua', 'rb') as f:
    my_script = f.read().decode('utf8')

# body of the request to Splash
json_body = {
    'url': 'https://httpbin.org/basic-auth/user/passwd',
    'remote_auth': basic_auth_header('user', 'passwd'),
    'crawlera_apikey': '<CRAWLERA-API-KEY>',
    'lua_source': my_script,
}

resp = requests.post(splash_url, json=json_body, 
    # if Splash itself is protected by HTTP Basic Auth:
    # auth=('SPLASH-USER', 'SPLASH-PASSWORD'),
)

print(resp.text)
```

**Comment by wflanagan** [comment]
So, specifically in the case of Crawlera, the system is setup with proxies defined in Splash, with their host, port, username, and password assigned there.. 

so, the flow is: ```Client -> (splash auth?) -> Splash (with lookup of proxy locally in configuration) ->  Crawlera -> (website auth - typically does NOT exist) -> website```

in this case, the system returns a Crawlera 200 response, but returns an empty body. ```<html><head></head><body></body></html>```.  

I'm basically doing every different config I can think of to try to get this to work--with defined proxies, with sending a proxy-url.. etc.

**Comment by kmike** [comment]
@wflanagan it looks like proxy auth is not working properly in /render endpoints, but it works in /execute endpoint, when the proxy is set using `request:set_proxy`.  I'm working on a fix now. 

Which way to configure proxies are you using?

**Comment by kmike** [comment]
Thanks @wflanagan for the bug report! I'll make a 2.3.1 release with a fix soon.

**Comment by wflanagan** [comment]
P.s. I'm not losing my mind! :-)

**Comment by kmike** [comment]
@wflanagan Splash 2.3.1 images are available; passing proxy URL should work now (at least it worked on the httpbin example which was failing before). Feel free to reopen this issue if it still doesn't work for you!
