### ISSUE TITLE
Is it possible to give splash:go() function a url that uses fragments?

### ISSUE THREAD

**Issue by Arti89** [scrapinghub/splash#609]
Hello everybody,

i'm trying to render some javascript webpage using scrapy-splash. Im currently writing a lua script to click serveral buttons to load additional content. Unfortunately a couple of my urls are using fragments like javascript parameters. See example below:

function main(splash)
  local url = "https://www.bet365.com/#/AS/B13/"
  assert(splash:go(url))
  assert(splash:wait(0.5))
  return {
    urls = splash:url()

  }
end

When i execute the script, i get "https://www.bet365.com/de/" as output. So everything after the fragment identifier (#) is been left away. Accordingly I can't render the correct page that way. Is there a way to pass a url with fragments to the splash:go() function?

Thanks.

**Comment by kmike** [comment]
Unfortunately bet365 website is blocked in my country, so I can't check it. But fragments definitely work, I just tried it on a couple of other websites. It seems website did a redirect in your case (not that the path is not the same - it has `/de/` added). You can check it by using HAR records (submit this URL to Splash UI and check the network panel).

**Comment by tejkumar51** [comment]
@kmike I have seen the same behavior
 i.e. for example the below URL has fragment "**_pageId=1_**" that got not propagated further (to a search api) as a redirect happened between.
But this is working in Chrome browser, I can see from the network tab.

**[http://www.gapfactory.com/browse/category.do?cid=1092773#pageId=1](http://www.gapfactory.com/browse/category.do?cid=1092773#pageId=1)**

Is there any work around for this? (Because I am preparing new URLs if a page has pagination and relying on fragment only and submitting them with "**SplashRequest**" )
Please tell me if I am missing anything here.
