### ISSUE TITLE
web scraping

### ISSUE THREAD

**Issue by suryansht98** [scrapinghub/splash#664]
i am having trouble in scraping edx.org website .
i am unable to fetch data using splash , scrapy-splash.
can u please hepl me on this issue

**Comment by RyanOM** [comment]
Hey @suryansht98 ,

I'm not sure what the problem is, but it looks more like a Splash usage question, not a concrete bug report. We usually suggest using https://stackoverflow.com (use tag **splash-js-render** and **scrapy-splash**) to get help with such issues. It is a good idea to provide more details when creating a stackoverflow question; currently it is impossible to debug and reproduce based on the problem description.
