### ISSUE TITLE
Splash load balancing

### ISSUE THREAD

**Issue by thsheep** [scrapinghub/splash#677]
@ kmike 

Can Splash match Nginx for load balancing？

Because a single Splash load is low

**Comment by thsheep** [comment]
@kmike

**Comment by thsheep** [comment]
I want to use multiple physical machines to do load balancing

**Comment by kmike** [comment]
@thsheep sure, you can do this, Splash can be load balanced just like any other HTTP server. HAProxy can be a better fit than nginx though, because nginx provides request queues only in its paid version. See example HAProxy config in https://github.com/TeamHG-Memex/aquarium. See also: https://splash.readthedocs.io/en/stable/faq.html#how-to-run-splash-in-production.

**Comment by thsheep** [comment]
@kmike 

thank you very much! The My Splash load cluster is already working fine

But don't know whether to hold Hold. Thanks again,

Work happy! ☺

**Comment by thsheep** [comment]
closes #24
