### ISSUE TITLE
Render characters to png

### ISSUE THREAD

**Issue by pierluigicdc** [scrapinghub/splash#715]
Hi,
i'm facing the same problem of issue #267 but with **BENGALI LANGUAGE** 

http://0.0.0.0:8050/info?wait=0.5&images=1&expand=1&timeout=3600.0&url=http%3A%2F%2Fwww.abasar.net%2F&lua_source=function+main%28splash%29%0D%0A++local+url+%3D+splash.args.url%0D%0A++assert%28splash%3Ago%28url%29%29%0D%0A++assert%28splash%3Await%280.5%29%29%0D%0A++return+%7B%0D%0A++++png+%3D+splash%3Apng%28%29%0D%0A++%7D%0D%0Aend

![image](https://user-images.githubusercontent.com/19147030/34841420-89180444-f708-11e7-9b29-45d2be6c6b1d.png)

Is there any settings can i use for fixing or managing it?
 
Can you help me?

Thanks.

**Comment by kmike** [comment]
Such issues happen when a font is not available in Docker image. It turns out Ubuntu 16.04 doesn't ship them by default. I've added Bengali fonts to the Docker image; the site seems to render fine now. 

You can either wait for next Splash release (3.1), or get an updated Docker image from Splash master (`docker pull scrapinghub/splash:master`, then `docker run -it -p8050:8050 --rm scrapinghub/splash:master`). Updated Docker image for Splash master should become available in a hour or so.
