### ISSUE TITLE
Splash server start

### ISSUE THREAD

**Issue by Hari-Guhan-s** [scrapinghub/splash#730]
I am using splash with scrapy,
I have pip installed splash and it says its successfully installed but i could find the splash running under 8050,

does it requires docker as mandatory or just pip is enough ?

If pip is enough then how to check splash is working ?

**Comment by kmike** [comment]
Hi @Hari-Guhan-s,

pip is not enough because some of Splash dependencies are not pip-installable. You need to at least install this webkit fork: https://github.com/annulen/webkit, QT 5.9 and a few other packages. 

Installation without Docker is documented for Ubuntu 16.04: http://splash.readthedocs.io/en/stable/install.html#ubuntu-16-04-manual-way - but it is for brave souls. If you want to install Splash in some other OS, you need to figure out how to do something similar to what https://github.com/scrapinghub/splash/blob/master/dockerfiles/splash/provision.sh script is doing. 

For practical needs I'd say Docker is the way to go. I use Docker even for local Splash development now. We only document how to install Splash in Ubuntu 16.04 because Docker image uses Ubuntu 16.04, so it is an easy thing to do. Providing instructions for non-Docker installation for various OSes and environments is just too much work.
