### ISSUE TITLE
Splash not rendering JavaScript for https://yourstory.com

### ISSUE THREAD

**Issue by parthjoshi2007** [scrapinghub/splash#783]
Hi,
I am trying to use Splash to render the following page [YourStory](https://yourstory.com). However, Splash is unable to render the page at all. All I can see is a blank screen in the screenshot. The page is accessible from both Chrome and Firefox. I have tried increasing the wait upto 15s and also using a larger viewport but it does not seem to be working.

**Comment by vosmith** [comment]
Some things you may want to look out for are your user-agent string and request headers.  Load YourStory in a normal browser, and using some debug tools look at the the headers that are being sent from your browser.  Try to replicate those headers when you call `splash:go{headers=my_custom_headers}`.

Returning a `splash:har()` might also shed some light into what the issue is.

**Comment by parthjoshi2007** [comment]
I came back to this issue recently and yourstory.com is rendering fine. Maybe it was an issue with the website itself. Closing this issue now.
