### ISSUE TITLE
Splash unable to render the webpage https://stanok.eu

### ISSUE THREAD

**Issue by B87** [scrapinghub/splash#994]
Hi all,

I'm trying to render this site with splash (shub instance) and I only get a white screenshot.

It's like the js code was not loaded even that I have a 40s wait time.

query params of my request from splash-ui : wait=0.5&images=1&expand=1&timeout=60.0&url=https%3A%2F%2Fstanok.eu%2Fcategory%2F46&lua_source=function+main(splash%2C+args)%0D%0A++splash%3Ago("https%3A%2F%2Fstanok.eu%2F")%0D%0A++splash%3Await(40)%0D%0A++return+{png%3Dsplash%3Apng()}%0D%0Aend

Any help would be appreciated.

**Comment by ByronAP** [comment]
I gave the site a quick rundown and well this may very well be the worst built site on the internet. It loads almost 9mb of data over 659+ requests... thats crazy... 

I am on a multi-gigabit connection on a crazy fast (cpu, ram, gpu) machine and it takes about 20 seconds for the browser to finally render a meaningful paint. So I can only imagine that splash may very well take minutes to actually complete this request if it can even make all those requests successfully.

It is so bad that chrome audits just error out... lol
So I figured I would try from someplace closer so I used webpagetest.org from London and well it is the worst site I have seen which is why you will have nothing but issues with this site.
Results: [https://www.webpagetest.org/result/200127_7A_877007c11627eee5adc18fc1b6292f46/](https://www.webpagetest.org/result/200127_7A_877007c11627eee5adc18fc1b6292f46/)

**Comment by B87** [comment]
Yes I know, it's crazy, I've been debbuging with the web tools...

Is the number of requests the biggest problem you see for splash?

Thanks mate!

**Comment by ByronAP** [comment]
Are you the dev? If so sorry, I didn't mean to come off as rude. But the first thing I would do is figure out why there are hundreds of js files and or why they are not bundled and minified into 1 file. Next I would do something about all the images that are way to big and too numerous (Example: https://stanok.eu/img/market/about-background.png why is this so so damn big). Then whatever images I have left I would compress using webp. Then I would find out why it is loading a ton of stuff over xhr (Example: https://stanok.eu/app/tpls/layouts/legal_page/fide_ru.html about page loads this seemingly for no reason). After that is fixed I would make sure the site can serve this stuff over http2. Oh and there is a 404 for a google tags page which needs to be fixed as well.

If you are not the dev you could clone the site locally with a crawler then bundle it all together and feed it to splash, but that is a headache and will not work for any dynamic content unless you modify the pages to pull the html from the site and retain the headers and cookies while using your local copy of the assets to build the page, which can then be fed into splash. Fun... 💥🔫 no thanks lol

**Comment by B87** [comment]
I'm not the dev of the site. I just wanna get the info in it.

The second approach sounds interesting though, just for the sake of learning (I'd probabbly avoid to crawl the site if it supposes a lot of truble). 

You have already done a lot for me... but, can you point me to the right direcction of how you would do that?

**Comment by ByronAP** [comment]
ok, so I gave this a second of thought... to accomplish just running it through splash without much hassle I think you could get this done fastest by using a caching proxy locally like squid and then going through that.

This will not decrease the requests or fix anything but it will serve them almost instantly once they are in the proxy cache, which you can preload.

**Comment by ByronAP** [comment]
You could also add a second layer that will combine and minify the files and provide http2 support. My thought here is to put the caching proxy on a server then put that server behind cloudflare. This will let the caching proxy do its thing and feed cloudflare, then cloudflare will take all that and apply its minification, compression, etc... and of course all of this is free stuff so no $ required (except maybe for the host to run the caching proxy, but that can be had for free or dirt cheap as well).
